### ISSUE TITLE
Transfer repo to organisation

### ISSUE THREAD

**Issue by ibes** [NANU-Wandel-Wege-entdecken/NANU-magazin-website#47]
- [x] moving the repo to the organization to a place/name that is great for the long run (if needed, rename the other repo for the website to a temporary name)
- [x] rewire the deployment process 
- [x] check if other things need to be updates to work with the new repo position
- [x] if needed, invite other maintainers to join the repo

**Comment by michael-voit** [comment]
Now this repo is public. Thank you for your reminders!
